"use strict";
// const message: string = "hello world";
// console.log(message);
let count = 0;
count += 1;
const message = "hello world";
const done = false;
const numbers = [1, 2, 3];
const messages = ["hello", "world"];
let mightBeUndefined = undefined;
let nullableNumber = null;
let color = "red";
color = "yellow";
